In [1]:
#This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
#and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
#and new users but also to provide a set of exercises for those who teach.


#If you find an error or think you've a better way to solve some of them, feel
#free to open an issue at <https://github.com/rougier/numpy-100>.
#File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
#hint: import … as`05093
import numpy as np


#### 2. Create a null vector of size 10 (★☆☆)
#hint: np.zeros`
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#hint: array[4]`
a= np.zeros(10)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [3]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#hint: arange`
b= np.arange(10, 50)
print(b, "\n")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 



In [4]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#hint: reshape`
c= np.arange(0, 9).reshape((3, 3))
print(c, "\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [5]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#hint: np.nonzero`
d= [1,2,0,0,4,0]
print(np.nonzero(d), "\n")

(array([0, 1, 4], dtype=int64),) 



In [6]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#hint: np.eye`
e= np.eye(3, 3)
print(e, "\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [7]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#hint: np.random.random`
f=np.random.random((3,3,3))
print(f, "\n")

[[[0.22988679 0.92739354 0.70751463]
  [0.50529982 0.82602683 0.39468587]
  [0.59758522 0.39509732 0.32171225]]

 [[0.9175826  0.79409245 0.94917681]
  [0.90365042 0.87487049 0.65559372]
  [0.91980977 0.4876296  0.52802147]]

 [[0.01592274 0.1158518  0.84039352]
  [0.39802422 0.21278037 0.11839757]
  [0.88075125 0.9262001  0.12935843]]] 



In [8]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#hint: min, max`
g=np.arange(0, 100).reshape((10, 10))
print(g, 'min is: ' + str(np.min(g)), 'max is: ' + str(np.max(g)), "\n")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] min is: 0 max is: 99 



In [9]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#hint: mean`
h= np.arange(0, 30)
print(h)
print(np.mean(h), "\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
14.5 



In [11]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#hint: np.diag`
print(np.diagflat([1,2,3,4], -1), "\n")

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]] 



In [13]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#hint: (x -mean)/std`
j=np.random.normal(0, 1, (3, 3))
print(j, "\n")

[[-0.2003333  -0.32454375 -0.67476325]
 [-1.84550339  1.90772441  0.10996429]
 [ 1.77041586 -0.60037695  0.41818622]] 



In [12]:
#### 13. How to find common values between two arrays? (★☆☆)
#hint: np.intersect1d`
k=np.arange(0, 9).reshape((3, 3))
l=np.arange(5, 14).reshape((3, 3))
kl= np.intersect1d(k, l)
print(kl, "\n")

[5 6 7 8] 



In [14]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#hint: sort`
m= np.arange(10, 20)
print(np.sort(m), "\n")

[10 11 12 13 14 15 16 17 18 19] 



In [15]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#hint: argmax`
n= np.arange(10, 20)
n[n == np.max(n)] = 0
print(n, "\n")

[10 11 12 13 14 15 16 17 18  0] 



In [16]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)`
o=np.random.normal(0, 1, (3, 3))
print(o)
#o= o - o.mean(axis=1, keepdims=True)
#print(o,"\n")

[[ 1.41655854  0.46189569 -0.30474901]
 [ 0.4188393  -2.64010219 -0.55683824]
 [-0.05843373  0.48027594  0.70124049]]


In [ ]:
#### 17. How to get the n largest values of an array (★★★)
#Z = np.arange(10000)
#np.random.shuffle(Z)
#nn = 5
#print(Z)
#hint: np.argsort | np.argpartition`

In [18]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#hint: np.where`
t=np.arange(0, 15)
np.random.shuffle(t)
t.reshape((5, 3))
x= np.where(n == np.max(n))
print(x)

(array([8], dtype=int64),)
